In [1]:
%pip install councilcount==0.10.2

Requirement already satisfied: councilcount==0.10.2 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (0.10.2)
Requirement already satisfied: certifi==2024.12.14 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (2024.12.14)
Requirement already satisfied: charset-normalizer==3.4.1 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (3.4.1)
Requirement already satisfied: geojson==3.2.0 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (3.2.0)
Requirement already satisfied: idna==3.10 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (3.10)
Requirement already satisfied: numpy==1.26.4 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (1.26.4)
Requirement already satisfied: pandas==2.2.3 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (2.2.3)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages (from councilcount==0.10.2) (2.9.0.post0)
^C

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
ERROR: Operation cancelled by user
Note: you may need to restart the kernel to use updated packages.

In [2]:
import councilcount as cc

In [3]:
cc.available_years()

5-Year ACS Surveys available: 2007-2011, 2012-2016, 2019-2023

Note: when using `councilcount` functions, only include the end year as the input for the year variable (e.g. '2023' for the 2019-2023 survey).

In [9]:
acs_year = 2023
cc.get_available_councilcount_codes(acs_year=acs_year)

Printing data dictionary for the 2023 5-Year ACS

,estimate_var_code,estimate_description,denominator_var_code,denominator_description
0,DP02_0001E,Total households,NaN,NaN
1,DP02_0014E,Households with one or more people under 18 years,DP02_0001E,Total households
2,DP02_0053E,"Population 3 years and over, enrolled in school",DP02_0088E,Total population
3,DP02_0054E,"Enrolled in nursery school, preschool",DP02_0053E,"Population 3 years and over, enrolled in school"
4,DP02_0055E,Enrolled in Kindergarten,DP02_0053E,"Population 3 years and over, enrolled in school"
...,...,...,...,...
122,DP05_0084E,"American Indian and Alaska Native alone, not H...",DP02_0088E,Total population
123,DP05_0085E,"Asian alone, not Hispanic or Latino",DP02_0088E,Total population
124,DP05_0086E,Native Hawaiian and Other Pacific Islander alo...,DP02_0088E,Total population
125,DP05_0087E,"Some other race alone, not Hispanic or Latino",DP02_0088E,Total population
126,DP05_0088E,"Two or more races, not Hispanic or Latino",DP02_0088E,Total population

In [43]:
acs_year = 2023
var_codes = [
"DP05_0003E", # Female
"DP02_0068E" # Adults with Bachelor’s degree or higher
]
geo = "nta" # "councildist", "policeprct", "schooldist", "nta", "communitydist", "modzcta", "borough", and "city" are acceptable inputs
boundary_year = 2023 # only necessary for Council District requests—2013 and 2023 are accetable inputs

cc.get_councilcount_estimates(acs_year=acs_year, geo=geo, var_codes=var_codes, boundary_year=boundary_year)

/Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages/councilcount/estimates.py:1205: UserWarning: `boundary_year` is only relevant for `geo = councildist`. Ignoring `boundary_year` input.
  warn("`boundary_year` is only relevant for `geo = councildist`. Ignoring `boundary_year` input.")

,nta,DP05_0003E,DP05_0003M,DP05_0003PE,DP05_0003PM,DP05_0003V,DP02_0068E,DP02_0068M,DP02_0068PE,DP02_0068PM,DP02_0068V
109,Allerton,17962,1279.0,53.53,2.23,4.33,4546,615.0,19.86,2.47,8.22
214,Alley Pond Park,0,NaN,0.00,NaN,NaN,34,36.0,87.18,134.89,64.37
255,Annadale-Huguenot-Prince's Bay-Woodrow,21807,1521.0,51.48,2.04,4.24,12966,1060.0,44.74,2.79,4.97
254,Arden Heights-Rossville,15956,1300.0,50.67,2.16,4.95,8155,817.0,36.83,2.82,6.09
158,Astoria (Central),23204,1354.0,48.44,1.66,3.55,23977,1488.0,61.81,2.73,3.77
...,...,...,...,...,...,...,...,...,...,...,...
22,Windsor Terrace-South Slope,12961,942.0,50.62,1.72,4.42,13676,1066.0,71.62,2.69,4.74
205,Woodhaven,20407,1391.0,49.55,1.85,4.14,7530,806.0,26.08,2.38,6.51
114,Woodlawn Cemetery,0,13.0,NaN,NaN,NaN,0,13.0,NaN,NaN,NaN
167,Woodside,24527,1572.0,51.22,1.54,3.90,11816,1007.0,31.80,2.14,5.18
81,Yankee Stadium-Macombs Dam Park,0,13.0,NaN,NaN,NaN,0,13.0,NaN,NaN,NaN

In [21]:
year = 2016
cc.get_bbl_population_estimates(year=year)

Printing BBL population estimates for 2016

       borough  block  lot   latitude  longitude  bbl_population_estimate
0           MN      2    3  40.701329 -74.011249                 0.000000
1           MN      3    1  40.702806 -74.015631                 0.000000
2           MN      3    2  40.701780 -74.013633                 0.000000
3           MN      3    3  40.701953 -74.013146                 0.000000
4           MN      3   10  40.700918 -74.014444                 0.000000
...        ...    ...  ...        ...        ...                      ...
851169      BX   5957  414  40.909343 -73.903802                 1.543554
851170      BX   5957  877  40.908822 -73.903893                 1.543554
851171      BX   5958    1  40.913012 -73.906822               130.800000
851172      BX   5958   10  40.911546 -73.905858               130.800000
851173      BX   5958  135  40.914176 -73.910663               130.800000

[851174 rows x 6 columns]

In [25]:
acs_year = 2023
census_api_key = "2f42b2b59ea3d5882dd01587b2e25769f000ed56"
cc.get_census_api_codes(acs_year=acs_year, census_api_key=census_api_key)

    variable_code                               variable_description
0      DP02_0001E     Estimate!!HOUSEHOLDS BY TYPE!!Total households
1      DP02_0002E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
2      DP02_0003E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
3      DP02_0004E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
4      DP02_0005E  Estimate!!HOUSEHOLDS BY TYPE!!Total households...
..            ...                                                ...
523    DP05_0090E  Estimate!!HISPANIC OR LATINO AND RACE!!Total p...
524    DP05_0091E                      Estimate!!Total housing units
525    DP05_0092E  Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...
526    DP05_0093E  Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...
527    DP05_0094E  Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...

[528 rows x 2 columns]

In [46]:
acs_year = 2011
demo_dict = {
    "DP02_0002E": "household", # Married-couple household
    "DP02_0025E": "person", # Males 15 and over
    "DP02_0026E": "person" # Never married males 15 and over
    }
geo = "councildist" # "councildist", "policeprct", "schooldist", "nta", "communitydist", "modzcta", "borough", and "city" are acceptable inputs
total_pop_code = "DP02_0088E" # Use this code for years 2020 and above. Use "DP02_0086E" for 2018 and earlier surveys. Use "DP02_0087E" for 2019. 
total_house_code = "DP02_0001E" # This code should be correct in most cases
boundary_year = 2013

table = cc.generate_new_estimates(acs_year=acs_year, demo_dict=demo_dict, geo=geo, census_api_key=census_api_key, total_pop_code=total_pop_code, total_house_code=total_house_code, boundary_year=None)

/Users/ravram/.pyenv/versions/3.9.17/lib/python3.9/site-packages/councilcount/estimates.py:1018: UserWarning: `boundary_year` must be set to 2013 or 2023 when `geo` is 'councildist'. Defaulting to 2023.
  warn("`boundary_year` must be set to 2013 or 2023 when `geo` is 'councildist'. Defaulting to 2023.")

In [ ]:
# generating the custom percent estimate and MOE      
table = cc.calc_percent_estimate(geo_df=table, num_code="DP02_0026E", denom_code="DP02_0025E")